/**
 * lang.js — مدير اللغة المشترك لجميع صفحات Anon
 */

const LangManager = (() => {

    const STORAGE_KEY = 'anon_lang';
    const SUPPORTED   = ['ar', 'en', 'fr', 'es', 'pt', 'de', 'ru', 'zh', 'hi', 'tr'];
    const DEFAULT     = 'ar';
    const RTL_LANGS   = ['ar'];

    const common = {
        ar: {
            nav_home:    'الرئيسية',
            nav_qs:      'الأسئلة',
            nav_skina:   'سكينة',
            nav_challenge: 'تحد',
            nav_profile: 'بروفايلي',
            search_placeholder: 'ابحث عن مستخدم...',
            no_notif:    'لا توجد إشعارات حالياً',
            more_notif:  'عرض المزيد من الإشعارات',
            replies_btn: 'الردود',
            install_app: 'ثبّت التطبيق على هاتفك 📲',
            install_sub: 'استخدمه بدون متصفح وبشكل أسرع',
            install_btn: 'تثبيت',
            later_btn:   'لاحقاً',
            ios_title:   '📲 ثبّت التطبيق على iPhone',
            ios_step1:   'اضغط على',
            ios_step2:   'مشاركة',
            ios_step3:   'ثم اختر',
            ios_step4:   '"إضافة إلى الشاشة الرئيسية"',
            ios_ok:      'فهمت ✓',
            installed_ok:'تم تثبيت التطبيق بنجاح 🎉',
            delete_confirm: 'هل تود الحذف؟',
            report_reason:  'سبب الإبلاغ؟',
            report_success: 'تم إرسال بلاغك ✨',
            error_generic:  'حدث خطأ، حاول مرة أخرى',
            deleted_ok:     'تم الحذف بنجاح',
            delete_error:   'حدث خطأ أثناء الحذف',
            dev_label:      'المطور',
            tabAll:          'الكل',
            tabPersonal:     'شخصي',
            tabShout:        'شاوت',
            personalLabel:   '🗣 سؤال شخصي',
            shoutLabel:      '📡 شاوت وارد',
            replyPublish:    'رد ونشر',
            publishAnswer:   'نشر الإجابة',
            replyPlaceholder:'اكتب ردك...',
            shoutReplyBtn:   'رد على الشاوت',
            shoutReplyPlaceholder: 'اكتب ردك على الشاوت...',
            sendShoutReply:  'إرسال الرد',
            anonLabel:       'مجهول',
            sentToAll:       'أرسل للجميع',
            emptyAll:        'لا توجد رسائل جديدة',
            emptyPersonal:   'لا توجد أسئلة شخصية',
            emptyShout:      'لا توجد شاوتات واردة',
            replyEmpty:      'اكتب ردك أولاً',
            newMsg:          'وصلتك رسالة جديدة! ✨',
            connError:       'حدث خطأ، حاول مجدداً',
            reportTitle:     '🚩 إبلاغ',
            reportPlaceholder:'اكتب سبب الإبلاغ...',
            reportSend:      'إرسال البلاغ',
            reportSuccess:   'تم إرسال البلاغ ✅',
            cancelBtn:       'تراجع',
            deleteTitle:     '🗑 حذف؟',
            deleteDesc:      'هل أنت متأكد؟ لا يمكن التراجع.',
            deleteBtn:       'حذف',
            deleted:         'تم الحذف ✓',
            replySuccess:    'تم الرد والنشر ✅',
            okBtn:           'حسناً',
            thread_title:             'الردود',
            thread_q_label:           'السؤال',
            thread_a_label:           'الإجابة',
            thread_like:              'إعجاب',
            thread_replies:           'الردود',
            thread_report:            'إبلاغ',
            thread_delete:            'حذف',
            thread_empty:             'لا توجد ردود بعد — كن أول من يرد!',
            thread_reply_placeholder: 'اكتب ردك هنا...',
            thread_anonymous:         'مجهول',
            thread_reported:          'تم الإبلاغ ✓',
            thread_delete_confirm:    'حذف التعليق؟',
            thread_sent:              'تم إرسال ردك ✓',
            thread_bad_word:          'تحتوي على كلمة غير لائقة',
            signin_title:    'تسجيل الدخول',
            signin_sub:      'أهلاً بك مجدداً في عالم الغموض',
            login_btn:       'دخول',
            forgot_pass:     'نسيت كلمة السر؟',
            new_user:        'مستخدم جديد؟',
            create_account:  'أنشئ حساباً',
            signup_title:    'حساب جديد',
            signup_sub:      'اكتشف من يراقبك في صمت',
            signup_btn:      'إنشاء الحساب',
            have_account:    'لديك حساب؟',
            login_link:      'سجل دخولك',
            verify_title:    'تفقد بريدك 📧',
            verify_sub:      'أرسلنا رابط التفعيل. اضغط عليه لتأكيد هويتك.',
            verify_done:     'تم التفعيل، دخول',
            complete_title:  'أكمل بياناتك 📋',
            complete_sub:    'بياناتك غير مكتملة، يرجى تعبئة الحقول التالية',
            missing_data:    '⚠️ البيانات الناقصة:',
            save_continue:   'حفظ والمتابعة',
            gender_label:    'الجنس',
            gender_male:     'ذكر',
            gender_female:   'أنثى',
            gender_other:    'أفضل عدم الإفصاح',
            age_ph:          'عمرك (13-100)',
            gender_required: 'يرجى اختيار الجنس',
            age_invalid:     'العمر بين 13 و100',
            privacy_accepted:'تم قبول السياسة ✅',
            privacy_required:'يجب الموافقة على السياسة',
            privacy_agree:   'أوافق على ',
            privacy_link:    'سياسة الخصوصية والشروط',
            privacy_age:     ' وأقر بأنني أعمر 13+',
            full_name_ph:    'الاسم الكامل',
            username_ph:     'اسم المستخدم (4+ حروف)',
            email_ph:        'البريد الإلكتروني',
            pass_ph:         'كلمة المرور',
            pass_new_ph:     'كلمة المرور (8+ حروف)',
            phone_ph:        'رقم الهاتف',
            phone_req_ph:    'رقم الهاتف (إجباري)',
            invalid_email:   'صيغة البريد غير صحيحة',
            blocked_email:   '⛔ البريد المؤقت غير مسموح به. استخدم بريداً حقيقياً.',
            untrusted_email: '⛔ يُسمح فقط بـ Gmail أو Outlook أو Yahoo وغيرها من المزودين الموثوقين.',
            wrong_credentials:'البريد أو كلمة المرور خطأ',
            name_required:   'الاسم الكامل مطلوب',
            phone_required:  'رقم الهاتف مطلوب',
            username_short:  'اسم المستخدم 4 حروف+',
            username_chars:  'حروف إنجليزية وأرقام فقط',
            username_taken:  'اسم المستخدم مأخوذ',
            email_taken:     'البريد مستخدم بالفعل',
            pass_short:      'كلمة المرور 8 أحرف+',
            too_many_attempts:'تجاوزت عدد المحاولات',
            network_error:   'تحقق من الاتصال بالإنترنت',
            signup_failed:   'فشل التسجيل',
            verify_email_first:'فعّل بريدك أولاً 📧',
            bad_word:        'الكلمة غير مسموح بها',
            save_error:      'خطأ أثناء الحفظ',
            enter_email_first:'اكتب بريدك أولاً',
            reset_sent:      'تم إرسال رابط الاستعادة 📧',
            reset_maybe_sent:'إذا كان البريد مسجلاً سيصلك الرابط',
            reset_wait:      'انتظر',
            minutes:         'دقيقة',
            no_updates:      'لا توجد تحديثات',
            updates_new:     'جديد',
            load_error:      'تعذر التحميل',
            about_title:     'المنصة المجهولة الأولى عربياً',
            about_sub:       'شارك رابطك، واكتشف من يراقبك في صمت.',
            stat_anon:       'مجهول',
            stat_secure:     'مشفر',
            stat_avail:      'متاح',
            stat_free_val:   'مجاني',
            stat_free:       'للأبد',
            feat_sec:        'أمان تام',
            feat_fast:       'سريع',
            feat_lang:       'متعدد اللغات',
            feat_rewards:    'مكافآت',
            feat_mobile:     'جوال',
            updates_title:   'آخر التحديثات',
            updates_loading: '⏳ جاري التحميل...',
            footer_privacy:  'سياسة الخصوصية',
            footer_terms:    'شروط الاستخدام',
            footer_contact:  'تواصل معنا',
            footer_rights:   'جميع الحقوق محفوظة',
        },
        en: {
            nav_home:    'Home',
            nav_qs:      'Inbox',
            nav_skina:   'Quiet',
            nav_challenge: 'Challenge',
            nav_profile: 'Profile',
            search_placeholder: 'Search for a user...',
            no_notif:    'No notifications yet',
            more_notif:  'View more notifications',
            replies_btn: 'Replies',
            install_app: 'Install the app on your phone 📲',
            install_sub: 'Use it without a browser, faster',
            install_btn: 'Install',
            later_btn:   'Later',
            ios_title:   '📲 Install on iPhone',
            ios_step1:   'Tap',
            ios_step2:   'Share',
            ios_step3:   'then choose',
            ios_step4:   '"Add to Home Screen"',
            ios_ok:      'Got it ✓',
            installed_ok:'App installed successfully 🎉',
            delete_confirm: 'Are you sure you want to delete?',
            report_reason:  'Reason for report?',
            report_success: 'Report sent ✨',
            error_generic:  'An error occurred, try again',
            deleted_ok:     'Deleted successfully',
            delete_error:   'Error while deleting',
            dev_label:      'Dev',
            tabAll:          'All',
            tabPersonal:     'Personal',
            tabShout:        'Shout',
            personalLabel:   '🗣 Personal Q',
            shoutLabel:      '📡 Incoming Shout',
            replyPublish:    'Reply & Post',
            publishAnswer:   'Publish Answer',
            replyPlaceholder:'Write your reply...',
            shoutReplyBtn:   'Reply to Shout',
            shoutReplyPlaceholder: 'Write your reply...',
            sendShoutReply:  'Send Reply',
            anonLabel:       'Anonymous',
            sentToAll:       'Sent to everyone',
            emptyAll:        'No new messages',
            emptyPersonal:   'No personal questions',
            emptyShout:      'No incoming shouts',
            replyEmpty:      'Write your reply first',
            newMsg:          'New message! ✨',
            connError:       'An error occurred, try again',
            reportTitle:     '🚩 Report',
            reportPlaceholder:'Describe the reason...',
            reportSend:      'Send Report',
            reportSuccess:   'Report submitted ✅',
            cancelBtn:       'Cancel',
            deleteTitle:     '🗑 Delete?',
            deleteDesc:      'Are you sure? This cannot be undone.',
            deleteBtn:       'Delete',
            deleted:         'Deleted ✓',
            replySuccess:    'Reply posted ✅',
            okBtn:           'OK',
            thread_title:             'Replies',
            thread_q_label:           'Question',
            thread_a_label:           'Answer',
            thread_like:              'Like',
            thread_replies:           'Replies',
            thread_report:            'Report',
            thread_delete:            'Delete',
            thread_empty:             'No replies yet — be the first!',
            thread_reply_placeholder: 'Write your reply here...',
            thread_anonymous:         'Anonymous',
            thread_reported:          'Reported ✓',
            thread_delete_confirm:    'Delete comment?',
            thread_sent:              'Reply sent ✓',
            thread_bad_word:          'Contains inappropriate language',
            signin_title:    'Sign In',
            signin_sub:      'Welcome back to the mystery',
            login_btn:       'Sign In',
            forgot_pass:     'Forgot password?',
            new_user:        'New user?',
            create_account:  'Create account',
            signup_title:    'New Account',
            signup_sub:      'Discover who watches you in silence',
            signup_btn:      'Create Account',
            have_account:    'Have an account?',
            login_link:      'Sign in',
            verify_title:    'Check your email 📧',
            verify_sub:      'We sent the activation link. Click it to verify your identity.',
            verify_done:     'Activated, Sign in',
            complete_title:  'Complete your info 📋',
            complete_sub:    'Your data is incomplete, please fill in the fields below',
            missing_data:    '⚠️ Missing data:',
            save_continue:   'Save & Continue',
            gender_label:    'Gender',
            gender_male:     'Male',
            gender_female:   'Female',
            gender_other:    'Prefer not to say',
            age_ph:          'Your age (13-100)',
            gender_required: 'Please select gender',
            age_invalid:     'Age must be between 13 and 100',
            privacy_accepted:'Policy accepted ✅',
            privacy_required:'Must accept the policy',
            privacy_agree:   'I agree to ',
            privacy_link:    'Privacy Policy & Terms',
            privacy_age:     " and I'm 13+ years old",
            full_name_ph:    'Full name',
            username_ph:     'Username (4+ chars)',
            email_ph:        'Email address',
            pass_ph:         'Password',
            pass_new_ph:     'Password (8+ chars)',
            phone_ph:        'Phone number',
            phone_req_ph:    'Phone (required)',
            invalid_email:   'Invalid email format',
            blocked_email:   '⛔ Temporary emails are not allowed. Use a real email.',
            untrusted_email: '⛔ Only trusted providers like Gmail, Outlook, or Yahoo are allowed.',
            wrong_credentials:'Wrong email or password',
            name_required:   'Full name is required',
            phone_required:  'Phone number is required',
            username_short:  'Username needs 4+ characters',
            username_chars:  'English letters and numbers only',
            username_taken:  'Username already taken',
            email_taken:     'Email already in use',
            pass_short:      'Password needs 8+ characters',
            too_many_attempts:'Too many attempts',
            network_error:   'Check your internet connection',
            signup_failed:   'Registration failed',
            verify_email_first:'Verify your email first 📧',
            bad_word:        'Inappropriate word',
            save_error:      'Error while saving',
            enter_email_first:'Enter your email first',
            reset_sent:      'Reset link sent 📧',
            reset_maybe_sent:'If registered, you will receive the link',
            reset_wait:      'Wait',
            minutes:         'minutes',
            no_updates:      'No updates',
            updates_new:     'new',
            load_error:      'Failed to load',
            about_title:     'The #1 Anonymous Platform',
            about_sub:       'Share your link & discover who watches you in silence.',
            stat_anon:       'Anonymous',
            stat_secure:     'Encrypted',
            stat_avail:      'Available',
            stat_free_val:   'Free',
            stat_free:       'Forever',
            feat_sec:        'Full security',
            feat_fast:       'Fast',
            feat_lang:       'Multilingual',
            feat_rewards:    'Rewards',
            feat_mobile:     'Mobile',
            updates_title:   'Latest Updates',
            updates_loading: '⏳ Loading...',
            footer_privacy:  'Privacy Policy',
            footer_terms:    'Terms of Use',
            footer_contact:  'Contact Us',
            footer_rights:   'All rights reserved',
        },
        fr: {
            nav_home:    'Accueil',
            nav_qs:      'Messages',
            nav_skina:   'Méditation',
            nav_challenge: 'Défi',
            nav_profile: 'Profil',
            search_placeholder: 'Rechercher un utilisateur...',
            no_notif:    'Aucune notification pour le moment',
            more_notif:  'Voir plus de notifications',
            replies_btn: 'Réponses',
            install_app: "Installez l'app sur votre téléphone 📲",
            install_sub: 'Utilisez-le sans navigateur, plus rapide',
            install_btn: 'Installer',
            later_btn:   'Plus tard',
            ios_title:   '📲 Installer sur iPhone',
            ios_step1:   'Appuyez sur',
            ios_step2:   'Partager',
            ios_step3:   'puis choisissez',
            ios_step4:   '"Ajouter à l\'écran d\'accueil"',
            ios_ok:      'Compris ✓',
            installed_ok:"Application installée avec succès 🎉",
            delete_confirm: 'Voulez-vous vraiment supprimer?',
            report_reason:  'Raison du signalement?',
            report_success: 'Signalement envoyé ✨',
            error_generic:  "Une erreur s'est produite, réessayez",
            deleted_ok:     'Supprimé avec succès',
            delete_error:   'Erreur lors de la suppression',
            dev_label:      'Dév',
            tabAll:          'Tout',
            tabPersonal:     'Perso',
            tabShout:        'Shout',
            personalLabel:   '🗣 Question perso',
            shoutLabel:      '📡 Shout reçu',
            replyPublish:    'Répondre & Publier',
            publishAnswer:   'Publier la réponse',
            replyPlaceholder:'Votre réponse...',
            shoutReplyBtn:   'Répondre au Shout',
            shoutReplyPlaceholder: 'Répondez au shout...',
            sendShoutReply:  'Envoyer',
            anonLabel:       'Anonyme',
            sentToAll:       'Envoyé à tous',
            emptyAll:        'Pas de nouveaux messages',
            emptyPersonal:   'Pas de questions personnelles',
            emptyShout:      'Pas de shouts entrants',
            replyEmpty:      "Écrivez votre réponse d'abord",
            newMsg:          'Nouveau message! ✨',
            connError:       "Une erreur s'est produite",
            reportTitle:     '🚩 Signaler',
            reportPlaceholder:'Décrivez la raison...',
            reportSend:      'Envoyer',
            reportSuccess:   'Signalement envoyé ✅',
            cancelBtn:       'Annuler',
            deleteTitle:     '🗑 Supprimer?',
            deleteDesc:      "Êtes-vous sûr? Impossible d'annuler.",
            deleteBtn:       'Supprimer',
            deleted:         'Supprimé ✓',
            replySuccess:    'Réponse publiée ✅',
            okBtn:           'OK',
            thread_title:             'Réponses',
            thread_q_label:           'Question',
            thread_a_label:           'Réponse',
            thread_like:              "J'aime",
            thread_replies:           'Réponses',
            thread_report:            'Signaler',
            thread_delete:            'Supprimer',
            thread_empty:             'Pas encore de réponses — soyez le premier!',
            thread_reply_placeholder: 'Écrivez votre réponse ici...',
            thread_anonymous:         'Anonyme',
            thread_reported:          'Signalé ✓',
            thread_delete_confirm:    'Supprimer le commentaire?',
            thread_sent:              'Réponse envoyée ✓',
            thread_bad_word:          'Contient un langage inapproprié',
            signin_title:    'Connexion',
            signin_sub:      'Bon retour dans le mystère',
            login_btn:       'Connexion',
            forgot_pass:     'Mot de passe oublié?',
            new_user:        'Nouvel utilisateur?',
            create_account:  'Créer un compte',
            signup_title:    'Nouveau compte',
            signup_sub:      'Découvrez qui vous regarde en silence',
            signup_btn:      'Créer le compte',
            have_account:    'Vous avez un compte?',
            login_link:      'Se connecter',
            verify_title:    'Vérifiez votre email 📧',
            verify_sub:      "Nous avons envoyé le lien d'activation. Cliquez dessus pour confirmer.",
            verify_done:     'Activé, Connexion',
            complete_title:  'Complétez vos infos 📋',
            complete_sub:    'Vos données sont incomplètes, veuillez remplir les champs ci-dessous',
            missing_data:    '⚠️ Données manquantes:',
            save_continue:   'Enregistrer et continuer',
            gender_label:    'Genre',
            gender_male:     'Homme',
            gender_female:   'Femme',
            gender_other:    'Préfère ne pas répondre',
            age_ph:          'Votre âge (13-100)',
            gender_required: 'Veuillez sélectionner le genre',
            age_invalid:     "L'âge doit être entre 13 et 100",
            privacy_accepted:'Politique acceptée ✅',
            privacy_required:'Doit accepter la politique',
            privacy_agree:   "J'accepte les ",
            privacy_link:    'Politique et Conditions',
            privacy_age:     " et j'ai 13+ ans",
            full_name_ph:    'Nom complet',
            username_ph:     "Nom d'utilisateur (4+)",
            email_ph:        'Adresse e-mail',
            pass_ph:         'Mot de passe',
            pass_new_ph:     'Mot de passe (8+ car.)',
            phone_ph:        'Numéro de téléphone',
            phone_req_ph:    'Téléphone (obligatoire)',
            invalid_email:   'Format email invalide',
            blocked_email:   '⛔ Les emails temporaires ne sont pas autorisés. Utilisez un vrai email.',
            untrusted_email: '⛔ Seuls les fournisseurs reconnus comme Gmail, Outlook ou Yahoo sont autorisés.',
            wrong_credentials:'Email ou mot de passe incorrect',
            name_required:   'Le nom complet est requis',
            phone_required:  'Numéro de téléphone requis',
            username_short:  "Nom d'utilisateur 4+ caractères",
            username_chars:  'Lettres et chiffres seulement',
            username_taken:  "Nom d'utilisateur déjà pris",
            email_taken:     'Email déjà utilisé',
            pass_short:      'Mot de passe 8+ caractères',
            too_many_attempts:'Trop de tentatives',
            network_error:   'Vérifiez votre connexion',
            signup_failed:   'Inscription échouée',
            verify_email_first:"Vérifiez votre email d'abord 📧",
            bad_word:        'Mot inapproprié',
            save_error:      'Erreur lors de la sauvegarde',
            enter_email_first:"Entrez votre email d'abord",
            reset_sent:      'Lien de réinitialisation envoyé 📧',
            reset_maybe_sent:'Si inscrit, vous recevrez le lien',
            reset_wait:      'Attendez',
            minutes:         'minutes',
            no_updates:      'Aucune mise à jour',
            updates_new:     'nouveau',
            load_error:      'Échec du chargement',
            about_title:     'La plateforme anonyme n°1',
            about_sub:       'Partagez votre lien et découvrez qui vous regarde en silence.',
            stat_anon:       'Anonyme',
            stat_secure:     'Chiffré',
            stat_avail:      'Disponible',
            stat_free_val:   'Gratuit',
            stat_free:       'Pour toujours',
            feat_sec:        'Sécurité totale',
            feat_fast:       'Rapide',
            feat_lang:       'Multilingue',
            feat_rewards:    'Récompenses',
            feat_mobile:     'Mobile',
            updates_title:   'Dernières mises à jour',
            updates_loading: '⏳ Chargement...',
            footer_privacy:  'Politique de confidentialité',
            footer_terms:    "Conditions d'utilisation",
            footer_contact:  'Nous contacter',
            footer_rights:   'Tous droits réservés',
        },
        es: {
            nav_home:    'Inicio',
            nav_qs:      'Mensajes',
            nav_skina:   'Calma',
            nav_challenge: 'Desafío',
            nav_profile: 'Perfil',
            search_placeholder: 'Buscar un usuario...',
            no_notif:    'Sin notificaciones por ahora',
            more_notif:  'Ver más notificaciones',
            replies_btn: 'Respuestas',
            install_app: 'Instala la app en tu teléfono 📲',
            install_sub: 'Úsala sin navegador, más rápido',
            install_btn: 'Instalar',
            later_btn:   'Después',
            ios_title:   '📲 Instalar en iPhone',
            ios_step1:   'Toca',
            ios_step2:   'Compartir',
            ios_step3:   'luego elige',
            ios_step4:   '"Agregar a pantalla de inicio"',
            ios_ok:      'Entendido ✓',
            installed_ok:'App instalada con éxito 🎉',
            delete_confirm: '¿Seguro que quieres eliminar?',
            report_reason:  '¿Motivo del reporte?',
            report_success: 'Reporte enviado ✨',
            error_generic:  'Ocurrió un error, inténtalo de nuevo',
            deleted_ok:     'Eliminado correctamente',
            delete_error:   'Error al eliminar',
            dev_label:      'Dev',
            tabAll:          'Todo',
            tabPersonal:     'Personal',
            tabShout:        'Shout',
            personalLabel:   '🗣 Pregunta personal',
            shoutLabel:      '📡 Shout entrante',
            replyPublish:    'Responder y publicar',
            publishAnswer:   'Publicar respuesta',
            replyPlaceholder:'Escribe tu respuesta...',
            shoutReplyBtn:   'Responder al Shout',
            shoutReplyPlaceholder: 'Escribe tu respuesta al shout...',
            sendShoutReply:  'Enviar respuesta',
            anonLabel:       'Anónimo',
            sentToAll:       'Enviado a todos',
            emptyAll:        'Sin mensajes nuevos',
            emptyPersonal:   'Sin preguntas personales',
            emptyShout:      'Sin shouts entrantes',
            replyEmpty:      'Escribe tu respuesta primero',
            newMsg:          '¡Nuevo mensaje! ✨',
            connError:       'Ocurrió un error, inténtalo de nuevo',
            reportTitle:     '🚩 Reportar',
            reportPlaceholder:'Describe el motivo...',
            reportSend:      'Enviar reporte',
            reportSuccess:   'Reporte enviado ✅',
            cancelBtn:       'Cancelar',
            deleteTitle:     '🗑 ¿Eliminar?',
            deleteDesc:      '¿Estás seguro? No se puede deshacer.',
            deleteBtn:       'Eliminar',
            deleted:         'Eliminado ✓',
            replySuccess:    'Respuesta publicada ✅',
            okBtn:           'OK',
            thread_title:             'Respuestas',
            thread_q_label:           'Pregunta',
            thread_a_label:           'Respuesta',
            thread_like:              'Me gusta',
            thread_replies:           'Respuestas',
            thread_report:            'Reportar',
            thread_delete:            'Eliminar',
            thread_empty:             'Sin respuestas aún — ¡sé el primero!',
            thread_reply_placeholder: 'Escribe tu respuesta aquí...',
            thread_anonymous:         'Anónimo',
            thread_reported:          'Reportado ✓',
            thread_delete_confirm:    '¿Eliminar comentario?',
            thread_sent:              'Respuesta enviada ✓',
            thread_bad_word:          'Contiene lenguaje inapropiado',
            signin_title:    'Iniciar sesión',
            signin_sub:      'Bienvenido de nuevo al misterio',
            login_btn:       'Entrar',
            forgot_pass:     '¿Olvidaste tu contraseña?',
            new_user:        '¿Usuario nuevo?',
            create_account:  'Crear cuenta',
            signup_title:    'Nueva cuenta',
            signup_sub:      'Descubre quién te observa en silencio',
            signup_btn:      'Crear cuenta',
            have_account:    '¿Ya tienes cuenta?',
            login_link:      'Iniciar sesión',
            verify_title:    'Revisa tu correo 📧',
            verify_sub:      'Enviamos el enlace de activación. Haz clic para verificar tu identidad.',
            verify_done:     'Activado, entrar',
            complete_title:  'Completa tu info 📋',
            complete_sub:    'Tus datos están incompletos, por favor llena los campos',
            missing_data:    '⚠️ Datos faltantes:',
            save_continue:   'Guardar y continuar',
            gender_label:    'Género',
            gender_male:     'Masculino',
            gender_female:   'Femenino',
            gender_other:    'Prefiero no decir',
            age_ph:          'Tu edad (13-100)',
            gender_required: 'Por favor selecciona el género',
            age_invalid:     'La edad debe estar entre 13 y 100',
            privacy_accepted:'Política aceptada ✅',
            privacy_required:'Debes aceptar la política',
            privacy_agree:   'Acepto ',
            privacy_link:    'Política de privacidad y Términos',
            privacy_age:     ' y confirmo que tengo 13+ años',
            full_name_ph:    'Nombre completo',
            username_ph:     'Usuario (4+ caracteres)',
            email_ph:        'Correo electrónico',
            pass_ph:         'Contraseña',
            pass_new_ph:     'Contraseña (8+ caracteres)',
            phone_ph:        'Número de teléfono',
            phone_req_ph:    'Teléfono (obligatorio)',
            invalid_email:   'Formato de correo inválido',
            blocked_email:   '⛔ Los correos temporales no están permitidos. Usa un correo real.',
            untrusted_email: '⛔ Solo se permiten proveedores como Gmail, Outlook o Yahoo.',
            wrong_credentials:'Correo o contraseña incorrectos',
            name_required:   'El nombre completo es obligatorio',
            phone_required:  'El número de teléfono es obligatorio',
            username_short:  'El usuario necesita 4+ caracteres',
            username_chars:  'Solo letras y números',
            username_taken:  'Nombre de usuario ya en uso',
            email_taken:     'Correo ya en uso',
            pass_short:      'La contraseña necesita 8+ caracteres',
            too_many_attempts:'Demasiados intentos',
            network_error:   'Verifica tu conexión a internet',
            signup_failed:   'Error en el registro',
            verify_email_first:'Verifica tu correo primero 📧',
            bad_word:        'Palabra inapropiada',
            save_error:      'Error al guardar',
            enter_email_first:'Ingresa tu correo primero',
            reset_sent:      'Enlace de recuperación enviado 📧',
            reset_maybe_sent:'Si el correo está registrado recibirás el enlace',
            reset_wait:      'Espera',
            minutes:         'minutos',
            no_updates:      'Sin actualizaciones',
            updates_new:     'nuevo',
            load_error:      'Error al cargar',
            about_title:     'La plataforma anónima #1',
            about_sub:       'Comparte tu enlace y descubre quién te observa en silencio.',
            stat_anon:       'Anónimo',
            stat_secure:     'Cifrado',
            stat_avail:      'Disponible',
            stat_free_val:   'Gratis',
            stat_free:       'Para siempre',
            feat_sec:        'Seguridad total',
            feat_fast:       'Rápido',
            feat_lang:       'Multilingüe',
            feat_rewards:    'Recompensas',
            feat_mobile:     'Móvil',
            updates_title:   'Últimas actualizaciones',
            updates_loading: '⏳ Cargando...',
            footer_privacy:  'Política de privacidad',
            footer_terms:    'Términos de uso',
            footer_contact:  'Contáctanos',
            footer_rights:   'Todos los derechos reservados',
        },
        pt: {
            nav_home:    'Início',
            nav_qs:      'Mensagens',
            nav_skina:   'Calma',
            nav_challenge: 'Desafio',
            nav_profile: 'Perfil',
            search_placeholder: 'Buscar um usuário...',
            no_notif:    'Sem notificações por enquanto',
            more_notif:  'Ver mais notificações',
            replies_btn: 'Respostas',
            install_app: 'Instale o app no seu celular 📲',
            install_sub: 'Use sem navegador, mais rápido',
            install_btn: 'Instalar',
            later_btn:   'Depois',
            ios_title:   '📲 Instalar no iPhone',
            ios_step1:   'Toque em',
            ios_step2:   'Compartilhar',
            ios_step3:   'depois escolha',
            ios_step4:   '"Adicionar à tela inicial"',
            ios_ok:      'Entendido ✓',
            installed_ok:'App instalado com sucesso 🎉',
            delete_confirm: 'Tem certeza que quer excluir?',
            report_reason:  'Motivo da denúncia?',
            report_success: 'Denúncia enviada ✨',
            error_generic:  'Ocorreu um erro, tente novamente',
            deleted_ok:     'Excluído com sucesso',
            delete_error:   'Erro ao excluir',
            dev_label:      'Dev',
            tabAll:          'Tudo',
            tabPersonal:     'Pessoal',
            tabShout:        'Shout',
            personalLabel:   '🗣 Pergunta pessoal',
            shoutLabel:      '📡 Shout recebido',
            replyPublish:    'Responder e publicar',
            publishAnswer:   'Publicar resposta',
            replyPlaceholder:'Escreva sua resposta...',
            shoutReplyBtn:   'Responder ao Shout',
            shoutReplyPlaceholder: 'Escreva sua resposta ao shout...',
            sendShoutReply:  'Enviar resposta',
            anonLabel:       'Anônimo',
            sentToAll:       'Enviado a todos',
            emptyAll:        'Sem novas mensagens',
            emptyPersonal:   'Sem perguntas pessoais',
            emptyShout:      'Sem shouts recebidos',
            replyEmpty:      'Escreva sua resposta primeiro',
            newMsg:          'Nova mensagem! ✨',
            connError:       'Ocorreu um erro, tente novamente',
            reportTitle:     '🚩 Denunciar',
            reportPlaceholder:'Descreva o motivo...',
            reportSend:      'Enviar denúncia',
            reportSuccess:   'Denúncia enviada ✅',
            cancelBtn:       'Cancelar',
            deleteTitle:     '🗑 Excluir?',
            deleteDesc:      'Tem certeza? Não é possível desfazer.',
            deleteBtn:       'Excluir',
            deleted:         'Excluído ✓',
            replySuccess:    'Resposta publicada ✅',
            okBtn:           'OK',
            thread_title:             'Respostas',
            thread_q_label:           'Pergunta',
            thread_a_label:           'Resposta',
            thread_like:              'Curtir',
            thread_replies:           'Respostas',
            thread_report:            'Denunciar',
            thread_delete:            'Excluir',
            thread_empty:             'Sem respostas ainda — seja o primeiro!',
            thread_reply_placeholder: 'Escreva sua resposta aqui...',
            thread_anonymous:         'Anônimo',
            thread_reported:          'Denunciado ✓',
            thread_delete_confirm:    'Excluir comentário?',
            thread_sent:              'Resposta enviada ✓',
            thread_bad_word:          'Contém linguagem inapropriada',
            signin_title:    'Entrar',
            signin_sub:      'Bem-vindo de volta ao mistério',
            login_btn:       'Entrar',
            forgot_pass:     'Esqueceu a senha?',
            new_user:        'Novo usuário?',
            create_account:  'Criar conta',
            signup_title:    'Nova conta',
            signup_sub:      'Descubra quem te observa em silêncio',
            signup_btn:      'Criar conta',
            have_account:    'Já tem conta?',
            login_link:      'Entrar',
            verify_title:    'Verifique seu e-mail 📧',
            verify_sub:      'Enviamos o link de ativação. Clique para verificar sua identidade.',
            verify_done:     'Ativado, entrar',
            complete_title:  'Complete suas informações 📋',
            complete_sub:    'Seus dados estão incompletos, preencha os campos abaixo',
            missing_data:    '⚠️ Dados faltando:',
            save_continue:   'Salvar e continuar',
            gender_label:    'Gênero',
            gender_male:     'Masculino',
            gender_female:   'Feminino',
            gender_other:    'Prefiro não dizer',
            age_ph:          'Sua idade (13-100)',
            gender_required: 'Por favor selecione o gênero',
            age_invalid:     'A idade deve estar entre 13 e 100',
            privacy_accepted:'Política aceita ✅',
            privacy_required:'Deve aceitar a política',
            privacy_agree:   'Concordo com ',
            privacy_link:    'Política de Privacidade e Termos',
            privacy_age:     ' e confirmo que tenho 13+ anos',
            full_name_ph:    'Nome completo',
            username_ph:     'Usuário (4+ caracteres)',
            email_ph:        'Endereço de e-mail',
            pass_ph:         'Senha',
            pass_new_ph:     'Senha (8+ caracteres)',
            phone_ph:        'Número de telefone',
            phone_req_ph:    'Telefone (obrigatório)',
            invalid_email:   'Formato de e-mail inválido',
            blocked_email:   '⛔ E-mails temporários não são permitidos. Use um e-mail real.',
            untrusted_email: '⛔ Apenas provedores como Gmail, Outlook ou Yahoo são permitidos.',
            wrong_credentials:'E-mail ou senha incorretos',
            name_required:   'O nome completo é obrigatório',
            phone_required:  'O número de telefone é obrigatório',
            username_short:  'O usuário precisa de 4+ caracteres',
            username_chars:  'Apenas letras e números',
            username_taken:  'Nome de usuário já em uso',
            email_taken:     'E-mail já em uso',
            pass_short:      'A senha precisa de 8+ caracteres',
            too_many_attempts:'Muitas tentativas',
            network_error:   'Verifique sua conexão com a internet',
            signup_failed:   'Falha no cadastro',
            verify_email_first:'Verifique seu e-mail primeiro 📧',
            bad_word:        'Palavra inapropriada',
            save_error:      'Erro ao salvar',
            enter_email_first:'Digite seu e-mail primeiro',
            reset_sent:      'Link de recuperação enviado 📧',
            reset_maybe_sent:'Se cadastrado, você receberá o link',
            reset_wait:      'Aguarde',
            minutes:         'minutos',
            no_updates:      'Sem atualizações',
            updates_new:     'novo',
            load_error:      'Falha ao carregar',
            about_title:     'A plataforma anônima #1',
            about_sub:       'Compartilhe seu link e descubra quem te observa em silêncio.',
            stat_anon:       'Anônimo',
            stat_secure:     'Criptografado',
            stat_avail:      'Disponível',
            stat_free_val:   'Grátis',
            stat_free:       'Para sempre',
            feat_sec:        'Segurança total',
            feat_fast:       'Rápido',
            feat_lang:       'Multilíngue',
            feat_rewards:    'Recompensas',
            feat_mobile:     'Celular',
            updates_title:   'Últimas atualizações',
            updates_loading: '⏳ Carregando...',
            footer_privacy:  'Política de privacidade',
            footer_terms:    'Termos de uso',
            footer_contact:  'Contate-nos',
            footer_rights:   'Todos os direitos reservados',
        },
        de: {
            nav_home:    'Startseite',
            nav_qs:      'Nachrichten',
            nav_skina:   'Ruhe',
            nav_challenge: 'Herausforderung',
            nav_profile: 'Profil',
            search_placeholder: 'Benutzer suchen...',
            no_notif:    'Noch keine Benachrichtigungen',
            more_notif:  'Mehr Benachrichtigungen anzeigen',
            replies_btn: 'Antworten',
            install_app: 'App auf deinem Handy installieren 📲',
            install_sub: 'Ohne Browser nutzen, schneller',
            install_btn: 'Installieren',
            later_btn:   'Später',
            ios_title:   '📲 Auf iPhone installieren',
            ios_step1:   'Tippe auf',
            ios_step2:   'Teilen',
            ios_step3:   'dann wähle',
            ios_step4:   '"Zum Home-Bildschirm"',
            ios_ok:      'Verstanden ✓',
            installed_ok:'App erfolgreich installiert 🎉',
            delete_confirm: 'Wirklich löschen?',
            report_reason:  'Grund der Meldung?',
            report_success: 'Meldung gesendet ✨',
            error_generic:  'Ein Fehler ist aufgetreten, versuche es erneut',
            deleted_ok:     'Erfolgreich gelöscht',
            delete_error:   'Fehler beim Löschen',
            dev_label:      'Entwickler',
            tabAll:          'Alle',
            tabPersonal:     'Persönlich',
            tabShout:        'Shout',
            personalLabel:   '🗣 Persönliche Frage',
            shoutLabel:      '📡 Eingehender Shout',
            replyPublish:    'Antworten & Veröffentlichen',
            publishAnswer:   'Antwort veröffentlichen',
            replyPlaceholder:'Schreibe deine Antwort...',
            shoutReplyBtn:   'Auf Shout antworten',
            shoutReplyPlaceholder: 'Schreibe deine Antwort auf den Shout...',
            sendShoutReply:  'Antwort senden',
            anonLabel:       'Anonym',
            sentToAll:       'An alle gesendet',
            emptyAll:        'Keine neuen Nachrichten',
            emptyPersonal:   'Keine persönlichen Fragen',
            emptyShout:      'Keine eingehenden Shouts',
            replyEmpty:      'Schreibe zuerst deine Antwort',
            newMsg:          'Neue Nachricht! ✨',
            connError:       'Ein Fehler ist aufgetreten, versuche es erneut',
            reportTitle:     '🚩 Melden',
            reportPlaceholder:'Beschreibe den Grund...',
            reportSend:      'Meldung senden',
            reportSuccess:   'Meldung eingereicht ✅',
            cancelBtn:       'Abbrechen',
            deleteTitle:     '🗑 Löschen?',
            deleteDesc:      'Bist du sicher? Dies kann nicht rückgängig gemacht werden.',
            deleteBtn:       'Löschen',
            deleted:         'Gelöscht ✓',
            replySuccess:    'Antwort veröffentlicht ✅',
            okBtn:           'OK',
            thread_title:             'Antworten',
            thread_q_label:           'Frage',
            thread_a_label:           'Antwort',
            thread_like:              'Gefällt mir',
            thread_replies:           'Antworten',
            thread_report:            'Melden',
            thread_delete:            'Löschen',
            thread_empty:             'Noch keine Antworten — sei der Erste!',
            thread_reply_placeholder: 'Schreibe deine Antwort hier...',
            thread_anonymous:         'Anonym',
            thread_reported:          'Gemeldet ✓',
            thread_delete_confirm:    'Kommentar löschen?',
            thread_sent:              'Antwort gesendet ✓',
            thread_bad_word:          'Enthält unangemessene Sprache',
            signin_title:    'Anmelden',
            signin_sub:      'Willkommen zurück im Geheimnis',
            login_btn:       'Anmelden',
            forgot_pass:     'Passwort vergessen?',
            new_user:        'Neuer Benutzer?',
            create_account:  'Konto erstellen',
            signup_title:    'Neues Konto',
            signup_sub:      'Entdecke, wer dich im Stillen beobachtet',
            signup_btn:      'Konto erstellen',
            have_account:    'Hast du ein Konto?',
            login_link:      'Anmelden',
            verify_title:    'Überprüfe deine E-Mail 📧',
            verify_sub:      'Wir haben den Aktivierungslink gesendet. Klicke darauf, um deine Identität zu bestätigen.',
            verify_done:     'Aktiviert, anmelden',
            complete_title:  'Vervollständige deine Daten 📋',
            complete_sub:    'Deine Daten sind unvollständig, bitte fülle die folgenden Felder aus',
            missing_data:    '⚠️ Fehlende Daten:',
            save_continue:   'Speichern & Weiter',
            gender_label:    'Geschlecht',
            gender_male:     'Männlich',
            gender_female:   'Weiblich',
            gender_other:    'Keine Angabe',
            age_ph:          'Dein Alter (13-100)',
            gender_required: 'Bitte Geschlecht auswählen',
            age_invalid:     'Alter muss zwischen 13 und 100 liegen',
            privacy_accepted:'Richtlinie akzeptiert ✅',
            privacy_required:'Richtlinie muss akzeptiert werden',
            privacy_agree:   'Ich stimme zu ',
            privacy_link:    'Datenschutzrichtlinie & Nutzungsbedingungen',
            privacy_age:     ' und bestätige, dass ich 13+ Jahre alt bin',
            full_name_ph:    'Vollständiger Name',
            username_ph:     'Benutzername (4+ Zeichen)',
            email_ph:        'E-Mail-Adresse',
            pass_ph:         'Passwort',
            pass_new_ph:     'Passwort (8+ Zeichen)',
            phone_ph:        'Telefonnummer',
            phone_req_ph:    'Telefon (erforderlich)',
            invalid_email:   'Ungültiges E-Mail-Format',
            blocked_email:   '⛔ Temporäre E-Mails sind nicht erlaubt. Verwende eine echte E-Mail.',
            untrusted_email: '⛔ Nur vertrauenswürdige Anbieter wie Gmail, Outlook oder Yahoo sind erlaubt.',
            wrong_credentials:'Falsche E-Mail oder falsches Passwort',
            name_required:   'Vollständiger Name ist erforderlich',
            phone_required:  'Telefonnummer ist erforderlich',
            username_short:  'Benutzername braucht 4+ Zeichen',
            username_chars:  'Nur englische Buchstaben und Zahlen',
            username_taken:  'Benutzername bereits vergeben',
            email_taken:     'E-Mail bereits in Verwendung',
            pass_short:      'Passwort braucht 8+ Zeichen',
            too_many_attempts:'Zu viele Versuche',
            network_error:   'Überprüfe deine Internetverbindung',
            signup_failed:   'Registrierung fehlgeschlagen',
            verify_email_first:'Bestätige zuerst deine E-Mail 📧',
            bad_word:        'Unangemessenes Wort',
            save_error:      'Fehler beim Speichern',
            enter_email_first:'Gib zuerst deine E-Mail ein',
            reset_sent:      'Link zum Zurücksetzen gesendet 📧',
            reset_maybe_sent:'Falls registriert, erhältst du den Link',
            reset_wait:      'Warten',
            minutes:         'Minuten',
            no_updates:      'Keine Updates',
            updates_new:     'neu',
            load_error:      'Laden fehlgeschlagen',
            about_title:     'Die anonyme Plattform Nr. 1',
            about_sub:       'Teile deinen Link und entdecke, wer dich im Stillen beobachtet.',
            stat_anon:       'Anonym',
            stat_secure:     'Verschlüsselt',
            stat_avail:      'Verfügbar',
            stat_free_val:   'Kostenlos',
            stat_free:       'Für immer',
            feat_sec:        'Volle Sicherheit',
            feat_fast:       'Schnell',
            feat_lang:       'Mehrsprachig',
            feat_rewards:    'Belohnungen',
            feat_mobile:     'Mobil',
            updates_title:   'Neueste Updates',
            updates_loading: '⏳ Laden...',
            footer_privacy:  'Datenschutzrichtlinie',
            footer_terms:    'Nutzungsbedingungen',
            footer_contact:  'Kontakt',
            footer_rights:   'Alle Rechte vorbehalten',
        },
        ru: {
            nav_home:    'Главная',
            nav_qs:      'Сообщения',
            nav_skina:   'Покой',
            nav_challenge: 'Вызов',
            nav_profile: 'Профиль',
            search_placeholder: 'Найти пользователя...',
            no_notif:    'Уведомлений пока нет',
            more_notif:  'Показать больше уведомлений',
            replies_btn: 'Ответы',
            install_app: 'Установи приложение на телефон 📲',
            install_sub: 'Используй без браузера, быстрее',
            install_btn: 'Установить',
            later_btn:   'Позже',
            ios_title:   '📲 Установить на iPhone',
            ios_step1:   'Нажми',
            ios_step2:   'Поделиться',
            ios_step3:   'затем выбери',
            ios_step4:   '"Добавить на экран «Домой»"',
            ios_ok:      'Понятно ✓',
            installed_ok:'Приложение успешно установлено 🎉',
            delete_confirm: 'Вы уверены, что хотите удалить?',
            report_reason:  'Причина жалобы?',
            report_success: 'Жалоба отправлена ✨',
            error_generic:  'Произошла ошибка, попробуйте снова',
            deleted_ok:     'Успешно удалено',
            delete_error:   'Ошибка при удалении',
            dev_label:      'Разработчик',
            tabAll:          'Все',
            tabPersonal:     'Личное',
            tabShout:        'Шаут',
            personalLabel:   '🗣 Личный вопрос',
            shoutLabel:      '📡 Входящий шаут',
            replyPublish:    'Ответить и опубликовать',
            publishAnswer:   'Опубликовать ответ',
            replyPlaceholder:'Напишите ответ...',
            shoutReplyBtn:   'Ответить на шаут',
            shoutReplyPlaceholder: 'Напишите ответ на шаут...',
            sendShoutReply:  'Отправить ответ',
            anonLabel:       'Аноним',
            sentToAll:       'Отправлено всем',
            emptyAll:        'Новых сообщений нет',
            emptyPersonal:   'Личных вопросов нет',
            emptyShout:      'Входящих шаутов нет',
            replyEmpty:      'Сначала напишите ответ',
            newMsg:          'Новое сообщение! ✨',
            connError:       'Произошла ошибка, попробуйте снова',
            reportTitle:     '🚩 Пожаловаться',
            reportPlaceholder:'Опишите причину...',
            reportSend:      'Отправить жалобу',
            reportSuccess:   'Жалоба подана ✅',
            cancelBtn:       'Отмена',
            deleteTitle:     '🗑 Удалить?',
            deleteDesc:      'Уверены? Это нельзя отменить.',
            deleteBtn:       'Удалить',
            deleted:         'Удалено ✓',
            replySuccess:    'Ответ опубликован ✅',
            okBtn:           'ОК',
            thread_title:             'Ответы',
            thread_q_label:           'Вопрос',
            thread_a_label:           'Ответ',
            thread_like:              'Нравится',
            thread_replies:           'Ответы',
            thread_report:            'Пожаловаться',
            thread_delete:            'Удалить',
            thread_empty:             'Ответов пока нет — будьте первым!',
            thread_reply_placeholder: 'Напишите ответ здесь...',
            thread_anonymous:         'Аноним',
            thread_reported:          'Жалоба подана ✓',
            thread_delete_confirm:    'Удалить комментарий?',
            thread_sent:              'Ответ отправлен ✓',
            thread_bad_word:          'Содержит неприемлемый язык',
            signin_title:    'Войти',
            signin_sub:      'Добро пожаловать обратно в тайну',
            login_btn:       'Войти',
            forgot_pass:     'Забыли пароль?',
            new_user:        'Новый пользователь?',
            create_account:  'Создать аккаунт',
            signup_title:    'Новый аккаунт',
            signup_sub:      'Узнай, кто наблюдает за тобой в тишине',
            signup_btn:      'Создать аккаунт',
            have_account:    'Уже есть аккаунт?',
            login_link:      'Войти',
            verify_title:    'Проверьте почту 📧',
            verify_sub:      'Мы отправили ссылку для активации. Нажмите, чтобы подтвердить личность.',
            verify_done:     'Активировано, войти',
            complete_title:  'Заполните данные 📋',
            complete_sub:    'Ваши данные неполные, пожалуйста, заполните поля ниже',
            missing_data:    '⚠️ Отсутствующие данные:',
            save_continue:   'Сохранить и продолжить',
            gender_label:    'Пол',
            gender_male:     'Мужской',
            gender_female:   'Женский',
            gender_other:    'Предпочитаю не указывать',
            age_ph:          'Ваш возраст (13-100)',
            gender_required: 'Пожалуйста, выберите пол',
            age_invalid:     'Возраст должен быть от 13 до 100',
            privacy_accepted:'Политика принята ✅',
            privacy_required:'Необходимо принять политику',
            privacy_agree:   'Я соглашаюсь с ',
            privacy_link:    'Политикой конфиденциальности и Условиями',
            privacy_age:     ' и подтверждаю, что мне 13+ лет',
            full_name_ph:    'Полное имя',
            username_ph:     'Имя пользователя (4+ символов)',
            email_ph:        'Адрес электронной почты',
            pass_ph:         'Пароль',
            pass_new_ph:     'Пароль (8+ символов)',
            phone_ph:        'Номер телефона',
            phone_req_ph:    'Телефон (обязательно)',
            invalid_email:   'Неверный формат email',
            blocked_email:   '⛔ Временные email не разрешены. Используйте настоящий email.',
            untrusted_email: '⛔ Разрешены только надёжные провайдеры: Gmail, Outlook, Yahoo.',
            wrong_credentials:'Неверный email или пароль',
            name_required:   'Полное имя обязательно',
            phone_required:  'Номер телефона обязателен',
            username_short:  'Имя пользователя 4+ символов',
            username_chars:  'Только латинские буквы и цифры',
            username_taken:  'Имя пользователя уже занято',
            email_taken:     'Email уже используется',
            pass_short:      'Пароль 8+ символов',
            too_many_attempts:'Слишком много попыток',
            network_error:   'Проверьте подключение к интернету',
            signup_failed:   'Ошибка регистрации',
            verify_email_first:'Сначала подтвердите email 📧',
            bad_word:        'Неприемлемое слово',
            save_error:      'Ошибка при сохранении',
            enter_email_first:'Сначала введите email',
            reset_sent:      'Ссылка для восстановления отправлена 📧',
            reset_maybe_sent:'Если email зарегистрирован, вы получите ссылку',
            reset_wait:      'Подождите',
            minutes:         'минут',
            no_updates:      'Нет обновлений',
            updates_new:     'новое',
            load_error:      'Не удалось загрузить',
            about_title:     'Анонимная платформа №1',
            about_sub:       'Поделитесь ссылкой и узнайте, кто наблюдает за вами в тишине.',
            stat_anon:       'Анонимно',
            stat_secure:     'Зашифровано',
            stat_avail:      'Доступно',
            stat_free_val:   'Бесплатно',
            stat_free:       'Навсегда',
            feat_sec:        'Полная безопасность',
            feat_fast:       'Быстро',
            feat_lang:       'Многоязычный',
            feat_rewards:    'Награды',
            feat_mobile:     'Мобильный',
            updates_title:   'Последние обновления',
            updates_loading: '⏳ Загрузка...',
            footer_privacy:  'Политика конфиденциальности',
            footer_terms:    'Условия использования',
            footer_contact:  'Связаться с нами',
            footer_rights:   'Все права защищены',
        },
        zh: {
            nav_home:    '首页',
            nav_qs:      '消息',
            nav_skina:   '静心',
            nav_challenge: '挑战',
            nav_profile: '我的',
            search_placeholder: '搜索用户...',
            no_notif:    '暂无通知',
            more_notif:  '查看更多通知',
            replies_btn: '回复',
            install_app: '将应用安装到手机 📲',
            install_sub: '无需浏览器，更快速',
            install_btn: '安装',
            later_btn:   '稍后',
            ios_title:   '📲 安装到 iPhone',
            ios_step1:   '点击',
            ios_step2:   '分享',
            ios_step3:   '然后选择',
            ios_step4:   '"添加到主屏幕"',
            ios_ok:      '明白了 ✓',
            installed_ok:'应用安装成功 🎉',
            delete_confirm: '确定要删除吗？',
            report_reason:  '举报原因？',
            report_success: '举报已发送 ✨',
            error_generic:  '出现错误，请重试',
            deleted_ok:     '删除成功',
            delete_error:   '删除时出错',
            dev_label:      '开发者',
            tabAll:          '全部',
            tabPersonal:     '个人',
            tabShout:        '喊话',
            personalLabel:   '🗣 个人问题',
            shoutLabel:      '📡 收到喊话',
            replyPublish:    '回复并发布',
            publishAnswer:   '发布回答',
            replyPlaceholder:'写下你的回复...',
            shoutReplyBtn:   '回复喊话',
            shoutReplyPlaceholder: '写下对喊话的回复...',
            sendShoutReply:  '发送回复',
            anonLabel:       '匿名',
            sentToAll:       '已发送给所有人',
            emptyAll:        '暂无新消息',
            emptyPersonal:   '暂无个人问题',
            emptyShout:      '暂无收到的喊话',
            replyEmpty:      '请先写下你的回复',
            newMsg:          '新消息！✨',
            connError:       '出现错误，请重试',
            reportTitle:     '🚩 举报',
            reportPlaceholder:'描述原因...',
            reportSend:      '发送举报',
            reportSuccess:   '举报已提交 ✅',
            cancelBtn:       '取消',
            deleteTitle:     '🗑 删除？',
            deleteDesc:      '确定吗？此操作无法撤销。',
            deleteBtn:       '删除',
            deleted:         '已删除 ✓',
            replySuccess:    '回复已发布 ✅',
            okBtn:           '好的',
            thread_title:             '回复',
            thread_q_label:           '问题',
            thread_a_label:           '回答',
            thread_like:              '点赞',
            thread_replies:           '回复',
            thread_report:            '举报',
            thread_delete:            '删除',
            thread_empty:             '暂无回复 — 成为第一个！',
            thread_reply_placeholder: '在这里写下你的回复...',
            thread_anonymous:         '匿名',
            thread_reported:          '已举报 ✓',
            thread_delete_confirm:    '删除评论？',
            thread_sent:              '回复已发送 ✓',
            thread_bad_word:          '包含不当语言',
            signin_title:    '登录',
            signin_sub:      '欢迎回到神秘世界',
            login_btn:       '登录',
            forgot_pass:     '忘记密码？',
            new_user:        '新用户？',
            create_account:  '创建账号',
            signup_title:    '新账号',
            signup_sub:      '发现谁在默默关注你',
            signup_btn:      '创建账号',
            have_account:    '已有账号？',
            login_link:      '登录',
            verify_title:    '查看您的邮箱 📧',
            verify_sub:      '我们已发送激活链接，点击它以验证您的身份。',
            verify_done:     '已激活，登录',
            complete_title:  '完善您的资料 📋',
            complete_sub:    '您的资料不完整，请填写以下字段',
            missing_data:    '⚠️ 缺失数据：',
            save_continue:   '保存并继续',
            gender_label:    '性别',
            gender_male:     '男',
            gender_female:   '女',
            gender_other:    '不愿透露',
            age_ph:          '您的年龄 (13-100)',
            gender_required: '请选择性别',
            age_invalid:     '年龄必须在 13 到 100 之间',
            privacy_accepted:'政策已接受 ✅',
            privacy_required:'必须接受政策',
            privacy_agree:   '我同意 ',
            privacy_link:    '隐私政策和条款',
            privacy_age:     ' 并确认我已满 13 岁',
            full_name_ph:    '全名',
            username_ph:     '用户名（4+ 字符）',
            email_ph:        '电子邮件地址',
            pass_ph:         '密码',
            pass_new_ph:     '密码（8+ 字符）',
            phone_ph:        '电话号码',
            phone_req_ph:    '电话（必填）',
            invalid_email:   '邮箱格式无效',
            blocked_email:   '⛔ 不允许使用临时邮箱，请使用真实邮箱。',
            untrusted_email: '⛔ 仅允许 Gmail、Outlook 或 Yahoo 等可信提供商。',
            wrong_credentials:'邮箱或密码错误',
            name_required:   '全名为必填项',
            phone_required:  '电话号码为必填项',
            username_short:  '用户名需要 4+ 个字符',
            username_chars:  '仅限英文字母和数字',
            username_taken:  '用户名已被使用',
            email_taken:     '邮箱已被使用',
            pass_short:      '密码需要 8+ 个字符',
            too_many_attempts:'尝试次数过多',
            network_error:   '请检查您的网络连接',
            signup_failed:   '注册失败',
            verify_email_first:'请先验证您的邮箱 📧',
            bad_word:        '包含不当词语',
            save_error:      '保存时出错',
            enter_email_first:'请先输入您的邮箱',
            reset_sent:      '重置链接已发送 📧',
            reset_maybe_sent:'如果邮箱已注册，您将收到链接',
            reset_wait:      '等待',
            minutes:         '分钟',
            no_updates:      '暂无更新',
            updates_new:     '新',
            load_error:      '加载失败',
            about_title:     '第一匿名平台',
            about_sub:       '分享您的链接，发现谁在默默关注您。',
            stat_anon:       '匿名',
            stat_secure:     '加密',
            stat_avail:      '可用',
            stat_free_val:   '免费',
            stat_free:       '永久',
            feat_sec:        '完全安全',
            feat_fast:       '快速',
            feat_lang:       '多语言',
            feat_rewards:    '奖励',
            feat_mobile:     '移动端',
            updates_title:   '最新更新',
            updates_loading: '⏳ 加载中...',
            footer_privacy:  '隐私政策',
            footer_terms:    '使用条款',
            footer_contact:  '联系我们',
            footer_rights:   '版权所有',
        },
        hi: {
            nav_home:    'होम',
            nav_qs:      'संदेश',
            nav_skina:   'शांति',
            nav_challenge: 'चुनौती',
            nav_profile: 'प्रोफ़ाइल',
            search_placeholder: 'उपयोगकर्ता खोजें...',
            no_notif:    'अभी कोई सूचना नहीं',
            more_notif:  'और सूचनाएं देखें',
            replies_btn: 'जवाब',
            install_app: 'अपने फ़ोन पर ऐप इंस्टॉल करें 📲',
            install_sub: 'ब्राउज़र के बिना, तेज़ी से उपयोग करें',
            install_btn: 'इंस्टॉल करें',
            later_btn:   'बाद में',
            ios_title:   '📲 iPhone पर इंस्टॉल करें',
            ios_step1:   'टैप करें',
            ios_step2:   'शेयर',
            ios_step3:   'फिर चुनें',
            ios_step4:   '"होम स्क्रीन पर जोड़ें"',
            ios_ok:      'समझ गया ✓',
            installed_ok:'ऐप सफलतापूर्वक इंस्टॉल हुआ 🎉',
            delete_confirm: 'क्या आप वाकई हटाना चाहते हैं?',
            report_reason:  'रिपोर्ट का कारण?',
            report_success: 'रिपोर्ट भेजी गई ✨',
            error_generic:  'कोई त्रुटि हुई, पुनः प्रयास करें',
            deleted_ok:     'सफलतापूर्वक हटाया गया',
            delete_error:   'हटाने में त्रुटि',
            dev_label:      'डेवलपर',
            tabAll:          'सभी',
            tabPersonal:     'व्यक्तिगत',
            tabShout:        'शाउट',
            personalLabel:   '🗣 व्यक्तिगत प्रश्न',
            shoutLabel:      '📡 आने वाला शाउट',
            replyPublish:    'जवाब दें और प्रकाशित करें',
            publishAnswer:   'उत्तर प्रकाशित करें',
            replyPlaceholder:'अपना जवाब लिखें...',
            shoutReplyBtn:   'शाउट का जवाब दें',
            shoutReplyPlaceholder: 'शाउट का जवाब लिखें...',
            sendShoutReply:  'जवाब भेजें',
            anonLabel:       'गुमनाम',
            sentToAll:       'सभी को भेजा गया',
            emptyAll:        'कोई नया संदेश नहीं',
            emptyPersonal:   'कोई व्यक्तिगत प्रश्न नहीं',
            emptyShout:      'कोई आने वाला शाउट नहीं',
            replyEmpty:      'पहले अपना जवाब लिखें',
            newMsg:          'नया संदेश! ✨',
            connError:       'कोई त्रुटि हुई, पुनः प्रयास करें',
            reportTitle:     '🚩 रिपोर्ट करें',
            reportPlaceholder:'कारण बताएं...',
            reportSend:      'रिपोर्ट भेजें',
            reportSuccess:   'रिपोर्ट सबमिट हुई ✅',
            cancelBtn:       'रद्द करें',
            deleteTitle:     '🗑 हटाएं?',
            deleteDesc:      'क्या आप सुनिश्चित हैं? इसे पूर्ववत नहीं किया जा सकता।',
            deleteBtn:       'हटाएं',
            deleted:         'हटाया गया ✓',
            replySuccess:    'जवाब प्रकाशित हुआ ✅',
            okBtn:           'ठीक है',
            thread_title:             'जवाब',
            thread_q_label:           'प्रश्न',
            thread_a_label:           'उत्तर',
            thread_like:              'पसंद',
            thread_replies:           'जवाब',
            thread_report:            'रिपोर्ट',
            thread_delete:            'हटाएं',
            thread_empty:             'अभी कोई जवाब नहीं — पहले बनें!',
            thread_reply_placeholder: 'यहाँ अपना जवाब लिखें...',
            thread_anonymous:         'गुमनाम',
            thread_reported:          'रिपोर्ट किया गया ✓',
            thread_delete_confirm:    'टिप्पणी हटाएं?',
            thread_sent:              'जवाब भेजा गया ✓',
            thread_bad_word:          'अनुचित भाषा है',
            signin_title:    'साइन इन',
            signin_sub:      'रहस्य की दुनिया में वापस स्वागत है',
            login_btn:       'लॉग इन',
            forgot_pass:     'पासवर्ड भूल गए?',
            new_user:        'नए उपयोगकर्ता?',
            create_account:  'खाता बनाएं',
            signup_title:    'नया खाता',
            signup_sub:      'जानें कौन चुपचाप आपको देख रहा है',
            signup_btn:      'खाता बनाएं',
            have_account:    'पहले से खाता है?',
            login_link:      'साइन इन करें',
            verify_title:    'अपना ईमेल जांचें 📧',
            verify_sub:      'हमने एक्टिवेशन लिंक भेजा है। अपनी पहचान सत्यापित करने के लिए क्लिक करें।',
            verify_done:     'सक्रिय हुआ, लॉग इन करें',
            complete_title:  'अपनी जानकारी पूरी करें 📋',
            complete_sub:    'आपका डेटा अधूरा है, कृपया नीचे दिए फ़ील्ड भरें',
            missing_data:    '⚠️ अनुपस्थित डेटा:',
            save_continue:   'सहेजें और जारी रखें',
            gender_label:    'लिंग',
            gender_male:     'पुरुष',
            gender_female:   'महिला',
            gender_other:    'बताना पसंद नहीं',
            age_ph:          'आपकी आयु (13-100)',
            gender_required: 'कृपया लिंग चुनें',
            age_invalid:     'आयु 13 से 100 के बीच होनी चाहिए',
            privacy_accepted:'नीति स्वीकार की गई ✅',
            privacy_required:'नीति स्वीकार करनी होगी',
            privacy_agree:   'मैं सहमत हूं ',
            privacy_link:    'गोपनीयता नीति और शर्तें',
            privacy_age:     ' और पुष्टि करता/करती हूं कि मेरी आयु 13+ है',
            full_name_ph:    'पूरा नाम',
            username_ph:     'उपयोगकर्ता नाम (4+ अक्षर)',
            email_ph:        'ईमेल पता',
            pass_ph:         'पासवर्ड',
            pass_new_ph:     'पासवर्ड (8+ अक्षर)',
            phone_ph:        'फ़ोन नंबर',
            phone_req_ph:    'फ़ोन (आवश्यक)',
            invalid_email:   'ईमेल प्रारूप अमान्य है',
            blocked_email:   '⛔ अस्थायी ईमेल की अनुमति नहीं है। असली ईमेल उपयोग करें।',
            untrusted_email: '⛔ केवल Gmail, Outlook या Yahoo जैसे विश्वसनीय प्रदाता अनुमत हैं।',
            wrong_credentials:'गलत ईमेल या पासवर्ड',
            name_required:   'पूरा नाम आवश्यक है',
            phone_required:  'फ़ोन नंबर आवश्यक है',
            username_short:  'उपयोगकर्ता नाम में 4+ अक्षर चाहिए',
            username_chars:  'केवल अंग्रेज़ी अक्षर और अंक',
            username_taken:  'उपयोगकर्ता नाम पहले से लिया गया है',
            email_taken:     'ईमेल पहले से उपयोग में है',
            pass_short:      'पासवर्ड में 8+ अक्षर चाहिए',
            too_many_attempts:'बहुत अधिक प्रयास',
            network_error:   'अपना इंटरनेट कनेक्शन जांचें',
            signup_failed:   'पंजीकरण विफल',
            verify_email_first:'पहले अपना ईमेल सत्यापित करें 📧',
            bad_word:        'अनुचित शब्द',
            save_error:      'सहेजने में त्रुटि',
            enter_email_first:'पहले अपना ईमेल दर्ज करें',
            reset_sent:      'रीसेट लिंक भेजा गया 📧',
            reset_maybe_sent:'यदि पंजीकृत है, तो आपको लिंक मिलेगा',
            reset_wait:      'प्रतीक्षा करें',
            minutes:         'मिनट',
            no_updates:      'कोई अपडेट नहीं',
            updates_new:     'नया',
            load_error:      'लोड करने में विफल',
            about_title:     'नंबर 1 गुमनाम प्लेटफ़ॉर्म',
            about_sub:       'अपना लिंक साझा करें और जानें कौन चुपचाप आपको देख रहा है।',
            stat_anon:       'गुमनाम',
            stat_secure:     'एन्क्रिप्टेड',
            stat_avail:      'उपलब्ध',
            stat_free_val:   'मुफ़्त',
            stat_free:       'हमेशा के लिए',
            feat_sec:        'पूर्ण सुरक्षा',
            feat_fast:       'तेज़',
            feat_lang:       'बहुभाषी',
            feat_rewards:    'पुरस्कार',
            feat_mobile:     'मोबाइल',
            updates_title:   'नवीनतम अपडेट',
            updates_loading: '⏳ लोड हो रहा है...',
            footer_privacy:  'गोपनीयता नीति',
            footer_terms:    'उपयोग की शर्तें',
            footer_contact:  'संपर्क करें',
            footer_rights:   'सर्वाधिकार सुरक्षित',
        },
        tr: {
            nav_home:    'Ana Sayfa',
            nav_qs:      'Mesajlar',
            nav_skina:   'Huzur',
            nav_challenge: 'Meydan Okuma',
            nav_profile: 'Profil',
            search_placeholder: 'Kullanıcı ara...',
            no_notif:    'Henüz bildirim yok',
            more_notif:  'Daha fazla bildirim gör',
            replies_btn: 'Yanıtlar',
            install_app: 'Uygulamayı telefonuna yükle 📲',
            install_sub: 'Tarayıcı olmadan kullan, daha hızlı',
            install_btn: 'Yükle',
            later_btn:   'Sonra',
            ios_title:   '📲 iPhone\'a Yükle',
            ios_step1:   'Dokun',
            ios_step2:   'Paylaş',
            ios_step3:   'sonra seç',
            ios_step4:   '"Ana Ekrana Ekle"',
            ios_ok:      'Anladım ✓',
            installed_ok:'Uygulama başarıyla yüklendi 🎉',
            delete_confirm: 'Silmek istediğinizden emin misiniz?',
            report_reason:  'Şikayet nedeni?',
            report_success: 'Şikayet gönderildi ✨',
            error_generic:  'Bir hata oluştu, tekrar deneyin',
            deleted_ok:     'Başarıyla silindi',
            delete_error:   'Silinirken hata oluştu',
            dev_label:      'Geliştirici',
            tabAll:          'Tümü',
            tabPersonal:     'Kişisel',
            tabShout:        'Shout',
            personalLabel:   '🗣 Kişisel Soru',
            shoutLabel:      '📡 Gelen Shout',
            replyPublish:    'Yanıtla ve Yayınla',
            publishAnswer:   'Yanıtı Yayınla',
            replyPlaceholder:'Yanıtını yaz...',
            shoutReplyBtn:   'Shout\'a Yanıtla',
            shoutReplyPlaceholder: 'Shout\'a yanıtını yaz...',
            sendShoutReply:  'Yanıt Gönder',
            anonLabel:       'Anonim',
            sentToAll:       'Herkese gönderildi',
            emptyAll:        'Yeni mesaj yok',
            emptyPersonal:   'Kişisel soru yok',
            emptyShout:      'Gelen shout yok',
            replyEmpty:      'Önce yanıtını yaz',
            newMsg:          'Yeni mesaj! ✨',
            connError:       'Bir hata oluştu, tekrar deneyin',
            reportTitle:     '🚩 Şikayet Et',
            reportPlaceholder:'Nedeni açıkla...',
            reportSend:      'Şikayet Gönder',
            reportSuccess:   'Şikayet iletildi ✅',
            cancelBtn:       'İptal',
            deleteTitle:     '🗑 Sil?',
            deleteDesc:      'Emin misiniz? Bu işlem geri alınamaz.',
            deleteBtn:       'Sil',
            deleted:         'Silindi ✓',
            replySuccess:    'Yanıt yayınlandı ✅',
            okBtn:           'Tamam',
            thread_title:             'Yanıtlar',
            thread_q_label:           'Soru',
            thread_a_label:           'Yanıt',
            thread_like:              'Beğen',
            thread_replies:           'Yanıtlar',
            thread_report:            'Şikayet Et',
            thread_delete:            'Sil',
            thread_empty:             'Henüz yanıt yok — ilk sen ol!',
            thread_reply_placeholder: 'Yanıtını buraya yaz...',
            thread_anonymous:         'Anonim',
            thread_reported:          'Şikayet edildi ✓',
            thread_delete_confirm:    'Yorum silinsin mi?',
            thread_sent:              'Yanıt gönderildi ✓',
            thread_bad_word:          'Uygunsuz dil içeriyor',
            signin_title:    'Giriş Yap',
            signin_sub:      'Gizemli dünyaya tekrar hoş geldiniz',
            login_btn:       'Giriş Yap',
            forgot_pass:     'Şifreni mi unuttun?',
            new_user:        'Yeni kullanıcı mısınız?',
            create_account:  'Hesap oluştur',
            signup_title:    'Yeni Hesap',
            signup_sub:      'Sizi sessizce kimin izlediğini keşfedin',
            signup_btn:      'Hesap Oluştur',
            have_account:    'Hesabınız var mı?',
            login_link:      'Giriş yap',
            verify_title:    'E-postanızı kontrol edin 📧',
            verify_sub:      'Aktivasyon bağlantısını gönderdik. Kimliğinizi doğrulamak için tıklayın.',
            verify_done:     'Aktive edildi, giriş yap',
            complete_title:  'Bilgilerini tamamla 📋',
            complete_sub:    'Verileriniz eksik, lütfen aşağıdaki alanları doldurun',
            missing_data:    '⚠️ Eksik veriler:',
            save_continue:   'Kaydet ve Devam Et',
            gender_label:    'Cinsiyet',
            gender_male:     'Erkek',
            gender_female:   'Kadın',
            gender_other:    'Belirtmek istemiyorum',
            age_ph:          'Yaşınız (13-100)',
            gender_required: 'Lütfen cinsiyet seçin',
            age_invalid:     'Yaş 13 ile 100 arasında olmalıdır',
            privacy_accepted:'Politika kabul edildi ✅',
            privacy_required:'Politikayı kabul etmelisiniz',
            privacy_agree:   'Kabul ediyorum ',
            privacy_link:    'Gizlilik Politikası ve Şartlar',
            privacy_age:     ' ve 13+ yaşında olduğumu onaylıyorum',
            full_name_ph:    'Tam adınız',
            username_ph:     'Kullanıcı adı (4+ karakter)',
            email_ph:        'E-posta adresi',
            pass_ph:         'Şifre',
            pass_new_ph:     'Şifre (8+ karakter)',
            phone_ph:        'Telefon numarası',
            phone_req_ph:    'Telefon (zorunlu)',
            invalid_email:   'Geçersiz e-posta formatı',
            blocked_email:   '⛔ Geçici e-postalara izin verilmez. Gerçek bir e-posta kullanın.',
            untrusted_email: '⛔ Yalnızca Gmail, Outlook veya Yahoo gibi güvenilir sağlayıcılara izin verilir.',
            wrong_credentials:'Yanlış e-posta veya şifre',
            name_required:   'Tam ad zorunludur',
            phone_required:  'Telefon numarası zorunludur',
            username_short:  'Kullanıcı adı 4+ karakter gerektirir',
            username_chars:  'Yalnızca İngilizce harf ve rakamlar',
            username_taken:  'Kullanıcı adı zaten alınmış',
            email_taken:     'E-posta zaten kullanımda',
            pass_short:      'Şifre 8+ karakter gerektirir',
            too_many_attempts:'Çok fazla deneme',
            network_error:   'İnternet bağlantınızı kontrol edin',
            signup_failed:   'Kayıt başarısız',
            verify_email_first:'Önce e-postanızı doğrulayın 📧',
            bad_word:        'Uygunsuz kelime',
            save_error:      'Kaydedilirken hata',
            enter_email_first:'Önce e-postanızı girin',
            reset_sent:      'Sıfırlama bağlantısı gönderildi 📧',
            reset_maybe_sent:'Kayıtlıysa bağlantıyı alacaksınız',
            reset_wait:      'Bekle',
            minutes:         'dakika',
            no_updates:      'Güncelleme yok',
            updates_new:     'yeni',
            load_error:      'Yüklenemedi',
            about_title:     '1 Numaralı Anonim Platform',
            about_sub:       'Bağlantınızı paylaşın ve sizi sessizce kimin izlediğini keşfedin.',
            stat_anon:       'Anonim',
            stat_secure:     'Şifreli',
            stat_avail:      'Mevcut',
            stat_free_val:   'Ücretsiz',
            stat_free:       'Sonsuza dek',
            feat_sec:        'Tam güvenlik',
            feat_fast:       'Hızlı',
            feat_lang:       'Çok dilli',
            feat_rewards:    'Ödüller',
            feat_mobile:     'Mobil',
            updates_title:   'Son Güncellemeler',
            updates_loading: '⏳ Yükleniyor...',
            footer_privacy:  'Gizlilik Politikası',
            footer_terms:    'Kullanım Şartları',
            footer_contact:  'Bize Ulaşın',
            footer_rights:   'Tüm hakları saklıdır',
        },
    }; // end common

    function get() {
        const saved = localStorage.getItem(STORAGE_KEY);
        return SUPPORTED.includes(saved) ? saved : DEFAULT;
    }

    function set(lang) {
    if (!SUPPORTED.includes(lang)) lang = DEFAULT;
    localStorage.setItem(STORAGE_KEY, lang);
    localStorage.setItem('appLang', lang);
    localStorage.setItem('quizLang', lang);
    apply(lang);
}

    function apply(lang) {
        if (!lang) lang = get();
        document.documentElement.lang = lang;
        document.documentElement.dir  = RTL_LANGS.includes(lang) ? 'rtl' : 'ltr';

        const tr = common[lang] || common[DEFAULT];

        document.querySelectorAll('[data-lang-key]').forEach(el => {
            const key = el.dataset.langKey;
            if (tr[key] !== undefined) {
                if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
                    el.placeholder = tr[key];
                } else {
                    el.textContent = tr[key];
                }
            }
        });

        // تحديث زر اللغة
        const langCurrentLabel = document.getElementById('langCurrentLabel');
        if (langCurrentLabel) langCurrentLabel.textContent = lang.toUpperCase();
        SUPPORTED.forEach(l => {
            const el = document.getElementById('check-' + l);
            if (el) el.textContent = l === lang ? '✓' : '';
        });

        // الـ select القديم لو موجود
        document.querySelectorAll('.lang-select-global').forEach(sel => {
            sel.value = lang;
        });

        document.dispatchEvent(new CustomEvent('langChanged', { detail: { lang, tr } }));
    }

    function init() {
        const lang = get();
        apply(lang);

        document.querySelectorAll('.lang-select-global').forEach(sel => {
            sel.value = lang;
            sel.addEventListener('change', (e) => set(e.target.value));
        });
    }

    return {
        init,
        get,
        set,
        apply,
        t: (key) => (common[get()]?.[key] ?? common[DEFAULT]?.[key] ?? key)
    };

})();

document.addEventListener('DOMContentLoaded', () => LangManager.init());
